# Generated by Django 4.2.4 on 2023-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first_site', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(default=False, help_text='Возможен торг или нет', verbose_name='торг'),
        ),
    ]
