# Generated by Django 4.2.4 on 2023-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first_site', '0003_advertisement_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='date',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
