# Generated by Django 4.2.4 on 2023-08-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_first_site', '0006_rename_created_at_advertisement_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='date',
            new_name='create_date',
        ),
    ]
