# Generated by Django 4.2.4 on 2023-08-18 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_first_site', '0007_rename_date_advertisement_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='create_date',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
