# Generated by Django 4.2.4 on 2023-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first_site', '0009_advertisement_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
