# Generated by Django 4.2.4 on 2023-08-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first_site', '0012_alter_advertisement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=0, upload_to='first_site/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
